# spring.application.name=demo
server:
  port: 8080
  servlet:
    context-path: /sample
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600

spring:
  redis:
    host: 127.0.0.1
    post: 6379
    password:
  session:
    store-type: redis
    redis:
      namespace: spring:session
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false